In [132]:
from pathlib import Path

import pandas as pd
import numpy as np

In [133]:
data_path = Path(
    "../data/processed/clean_womens_shoes.parquet"
)

shoes = pd.read_parquet(data_path)

print("Dataset shape:", shoes.shape)
shoes.head()

Dataset shape: (53176, 10)

,train_id,name,item_condition_id,category_name,brand_name,price,shipping,item_description,shoe_type,condition_group
0,14,HOLD for Dogs2016 Minnetonka boots,3,Women/Shoes/Boots,UGG Australia,43.0,0,Authentic. Suede fringe boots. Great condition...,Boots,Condition 3
1,70,Adidas Ultraboost Shoes,3,Women/Shoes/Athletic,Adidas,61.0,0,Overall good condition. A few signs of wear,Athletic,Condition 3
2,107,Boots NWT 6.5,1,Women/Shoes/Boots,Merona,13.0,1,Merona short boot new with tag size 6.5 come j...,Boots,Condition 1
3,108,New Duck Boots sz.7.5,1,Women/Shoes/Boots,Boulevard Boutique,38.0,0,New Duck Boots Sz.7.5 Stock up on These Trendy...,Boots,Condition 1
4,115,Steve Madden wedges,2,Women/Shoes/Pumps,Steve Madden,25.0,1,Never worn!!! Brown leather strap wedges!,Pumps,Condition 2

In [134]:
brand_condition_summary = (
    shoes
    .groupby(
        [
            "brand_name",
            "shoe_type",
            "condition_group"
        ]
    )
    .agg(
        listing_count=("price", "size"),
        median_price=("price", "median")
    )
    .reset_index()
)

brand_condition_summary.head(20)

,brand_name,shoe_type,condition_group,listing_count,median_price
0,7 For All Mankind®,Sandals,Condition 2,1,22.0
1,A Bathing Ape,Sandals,Condition 1,1,20.0
2,A Pea In The Pod,Boots,Condition 4–5,1,10.0
3,A Pea In The Pod,Sandals,Condition 3,1,24.0
4,A.L.C.,Pumps,Condition 3,1,17.0
5,A.P.C.,Pumps,Condition 2,1,11.0
6,AB Studio,Boots,Condition 1,1,159.0
7,AB Studio,Loafers & Slip-Ons,Condition 3,1,20.0
8,AB Studio,Sandals,Condition 2,1,16.0
9,AKIRA,Boots,Condition 1,1,35.0
10,AKIRA,Boots,Condition 3,1,13.0
11,ALDO,Boots,Condition 1,13,46.0
12,ALDO,Boots,Condition 2,31,31.0
13,ALDO,Boots,Condition 3,52,23.0
14,ALDO,Boots,Condition 4–5,9,12.0
15,ALDO,Fashion Sneakers,Condition 1,2,53.5
16,ALDO,Fashion Sneakers,Condition 2,9,31.0
17,ALDO,Fashion Sneakers,Condition 3,14,20.5
18,ALDO,Flats,Condition 1,7,23.0
19,ALDO,Flats,Condition 2,8,20.5

In [135]:
condition_prices = (
    brand_condition_summary
    .pivot(
        index=[
            "brand_name",
            "shoe_type"
        ],
        columns="condition_group",
        values="median_price"
    )
    .reset_index()
)

condition_prices.head(20)

condition_group,brand_name,shoe_type,Condition 1,Condition 2,Condition 3,Condition 4–5
0,7 For All Mankind®,Sandals,NaN,22.0,NaN,NaN
1,A Bathing Ape,Sandals,20.0,NaN,NaN,NaN
2,A Pea In The Pod,Boots,NaN,NaN,NaN,10.0
3,A Pea In The Pod,Sandals,NaN,NaN,24.0,NaN
4,A.L.C.,Pumps,NaN,NaN,17.0,NaN
5,A.P.C.,Pumps,NaN,11.0,NaN,NaN
6,AB Studio,Boots,159.0,NaN,NaN,NaN
7,AB Studio,Loafers & Slip-Ons,NaN,NaN,20.0,NaN
8,AB Studio,Sandals,NaN,16.0,NaN,NaN
9,AKIRA,Boots,35.0,NaN,13.0,NaN
10,ALDO,Boots,46.0,31.0,23.0,12.0
11,ALDO,Fashion Sneakers,53.5,31.0,20.5,NaN
12,ALDO,Flats,23.0,20.5,15.0,8.0
13,ALDO,Loafers & Slip-Ons,NaN,20.0,20.5,NaN
14,ALDO,Pumps,31.0,20.0,20.0,14.0
15,ALDO,Sandals,22.5,21.5,16.0,7.0
16,ANDREA FENZI,Pumps,21.0,NaN,NaN,NaN
17,ANGL,Pumps,NaN,16.0,NaN,NaN
18,ASICS,Athletic,48.0,31.0,24.0,16.0
19,ASICS,Fashion Sneakers,75.0,29.5,23.0,NaN

In [136]:
condition_counts = (
    brand_condition_summary
    .pivot(
        index=[
            "brand_name",
            "shoe_type"
        ],
        columns="condition_group",
        values="listing_count"
    )
    .reset_index()
)

condition_counts.head(20)

condition_group,brand_name,shoe_type,Condition 1,Condition 2,Condition 3,Condition 4–5
0,7 For All Mankind®,Sandals,NaN,1.0,NaN,NaN
1,A Bathing Ape,Sandals,1.0,NaN,NaN,NaN
2,A Pea In The Pod,Boots,NaN,NaN,NaN,1.0
3,A Pea In The Pod,Sandals,NaN,NaN,1.0,NaN
4,A.L.C.,Pumps,NaN,NaN,1.0,NaN
5,A.P.C.,Pumps,NaN,1.0,NaN,NaN
6,AB Studio,Boots,1.0,NaN,NaN,NaN
7,AB Studio,Loafers & Slip-Ons,NaN,NaN,1.0,NaN
8,AB Studio,Sandals,NaN,1.0,NaN,NaN
9,AKIRA,Boots,1.0,NaN,1.0,NaN
10,ALDO,Boots,13.0,31.0,52.0,9.0
11,ALDO,Fashion Sneakers,2.0,9.0,14.0,NaN
12,ALDO,Flats,7.0,8.0,21.0,1.0
13,ALDO,Loafers & Slip-Ons,NaN,3.0,2.0,NaN
14,ALDO,Pumps,11.0,41.0,78.0,9.0
15,ALDO,Sandals,8.0,16.0,26.0,2.0
16,ANDREA FENZI,Pumps,1.0,NaN,NaN,NaN
17,ANGL,Pumps,NaN,1.0,NaN,NaN
18,ASICS,Athletic,42.0,83.0,184.0,20.0
19,ASICS,Fashion Sneakers,1.0,2.0,2.0,NaN

In [137]:
condition_analysis = condition_prices.merge(
    condition_counts,
    on=[
        "brand_name",
        "shoe_type"
    ],
    suffixes=(
        "_median_price",
        "_listing_count"
    )
)

condition_analysis.head(20)

condition_group,brand_name,shoe_type,Condition 1_median_price,Condition 2_median_price,Condition 3_median_price,Condition 4–5_median_price,Condition 1_listing_count,Condition 2_listing_count,Condition 3_listing_count,Condition 4–5_listing_count
0,7 For All Mankind®,Sandals,NaN,22.0,NaN,NaN,NaN,1.0,NaN,NaN
1,A Bathing Ape,Sandals,20.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN
2,A Pea In The Pod,Boots,NaN,NaN,NaN,10.0,NaN,NaN,NaN,1.0
3,A Pea In The Pod,Sandals,NaN,NaN,24.0,NaN,NaN,NaN,1.0,NaN
4,A.L.C.,Pumps,NaN,NaN,17.0,NaN,NaN,NaN,1.0,NaN
5,A.P.C.,Pumps,NaN,11.0,NaN,NaN,NaN,1.0,NaN,NaN
6,AB Studio,Boots,159.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN
7,AB Studio,Loafers & Slip-Ons,NaN,NaN,20.0,NaN,NaN,NaN,1.0,NaN
8,AB Studio,Sandals,NaN,16.0,NaN,NaN,NaN,1.0,NaN,NaN
9,AKIRA,Boots,35.0,NaN,13.0,NaN,1.0,NaN,1.0,NaN
10,ALDO,Boots,46.0,31.0,23.0,12.0,13.0,31.0,52.0,9.0
11,ALDO,Fashion Sneakers,53.5,31.0,20.5,NaN,2.0,9.0,14.0,NaN
12,ALDO,Flats,23.0,20.5,15.0,8.0,7.0,8.0,21.0,1.0
13,ALDO,Loafers & Slip-Ons,NaN,20.0,20.5,NaN,NaN,3.0,2.0,NaN
14,ALDO,Pumps,31.0,20.0,20.0,14.0,11.0,41.0,78.0,9.0
15,ALDO,Sandals,22.5,21.5,16.0,7.0,8.0,16.0,26.0,2.0
16,ANDREA FENZI,Pumps,21.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN
17,ANGL,Pumps,NaN,16.0,NaN,NaN,NaN,1.0,NaN,NaN
18,ASICS,Athletic,48.0,31.0,24.0,16.0,42.0,83.0,184.0,20.0
19,ASICS,Fashion Sneakers,75.0,29.5,23.0,NaN,1.0,2.0,2.0,NaN

In [138]:
minimum_listings = 10

condition_analysis["condition_2_retention"] = np.where(
    (
        condition_analysis["Condition 1_listing_count"] >= minimum_listings
    )
    & (
        condition_analysis["Condition 2_listing_count"] >= minimum_listings
    ),
    (
        condition_analysis["Condition 2_median_price"]
        / condition_analysis["Condition 1_median_price"]
    ),
    np.nan
)

condition_analysis["condition_3_retention"] = np.where(
    (
        condition_analysis["Condition 1_listing_count"] >= minimum_listings
    )
    & (
        condition_analysis["Condition 3_listing_count"] >= minimum_listings
    ),
    (
        condition_analysis["Condition 3_median_price"]
        / condition_analysis["Condition 1_median_price"]
    ),
    np.nan
)

condition_analysis["condition_4_5_retention"] = np.where(
    (
        condition_analysis["Condition 1_listing_count"] >= minimum_listings
    )
    & (
        condition_analysis["Condition 4–5_listing_count"] >= minimum_listings
    ),
    (
        condition_analysis["Condition 4–5_median_price"]
        / condition_analysis["Condition 1_median_price"]
    ),
    np.nan
)

condition_analysis[
    [
        "brand_name",
        "shoe_type",
        "condition_2_retention",
        "condition_3_retention",
        "condition_4_5_retention"
    ]
].head(20)

condition_group,brand_name,shoe_type,condition_2_retention,condition_3_retention,condition_4_5_retention
0,7 For All Mankind®,Sandals,NaN,NaN,NaN
1,A Bathing Ape,Sandals,NaN,NaN,NaN
2,A Pea In The Pod,Boots,NaN,NaN,NaN
3,A Pea In The Pod,Sandals,NaN,NaN,NaN
4,A.L.C.,Pumps,NaN,NaN,NaN
5,A.P.C.,Pumps,NaN,NaN,NaN
6,AB Studio,Boots,NaN,NaN,NaN
7,AB Studio,Loafers & Slip-Ons,NaN,NaN,NaN
8,AB Studio,Sandals,NaN,NaN,NaN
9,AKIRA,Boots,NaN,NaN,NaN
10,ALDO,Boots,0.673913,0.500000,NaN
11,ALDO,Fashion Sneakers,NaN,NaN,NaN
12,ALDO,Flats,NaN,NaN,NaN
13,ALDO,Loafers & Slip-Ons,NaN,NaN,NaN
14,ALDO,Pumps,0.645161,0.645161,NaN
15,ALDO,Sandals,NaN,NaN,NaN
16,ANDREA FENZI,Pumps,NaN,NaN,NaN
17,ANGL,Pumps,NaN,NaN,NaN
18,ASICS,Athletic,0.645833,0.500000,0.333333
19,ASICS,Fashion Sneakers,NaN,NaN,NaN

In [139]:
retention_availability = pd.Series({
    "Condition 2 comparisons": (
        condition_analysis["condition_2_retention"].notna().sum()
    ),
    "Condition 3 comparisons": (
        condition_analysis["condition_3_retention"].notna().sum()
    ),
    "Condition 4-5 comparisons": (
        condition_analysis["condition_4_5_retention"].notna().sum()
    )
})

retention_availability

Condition 2 comparisons      129
Condition 3 comparisons      133
Condition 4-5 comparisons     46
dtype: int64

In [140]:
usable_condition_analysis = condition_analysis[
    condition_analysis[
        [
            "condition_2_retention",
            "condition_3_retention",
            "condition_4_5_retention"
        ]
    ].notna().any(axis=1)
].copy()

print("Total brand-shoe combinations:", len(condition_analysis))
print("Combinations with at least one retention result:", len(usable_condition_analysis))

usable_condition_analysis[
    [
        "brand_name",
        "shoe_type",
        "condition_2_retention",
        "condition_3_retention",
        "condition_4_5_retention"
    ]
].head(20)

Total brand-shoe combinations: 2025
Combinations with at least one retention result: 135

condition_group,brand_name,shoe_type,condition_2_retention,condition_3_retention,condition_4_5_retention
10,ALDO,Boots,0.673913,0.500000,NaN
14,ALDO,Pumps,0.645161,0.645161,NaN
18,ASICS,Athletic,0.645833,0.500000,0.333333
30,Adidas,Athletic,0.528302,0.311321,0.179245
32,Adidas,Fashion Sneakers,0.772727,0.621212,0.272727
35,Adidas,Sandals,0.750000,0.500000,NaN
82,American Eagle,Boots,0.954545,0.772727,NaN
84,American Eagle,Flats,1.000000,0.833333,NaN
87,American Eagle,Sandals,0.875000,0.750000,NaN
133,Ariat,Boots,0.830986,0.676056,0.436620
189,BCBGeneration,Pumps,0.636364,0.484848,NaN
266,Birkenstock,Sandals,0.782051,0.589744,0.333333
306,Brooks,Athletic,0.689655,0.448276,0.327586
386,Chaco,Sandals,0.925620,0.925620,0.504132
396,Chanel,Flats,0.461095,0.590778,NaN
406,Charlotte Russe,Boots,0.807692,0.653846,NaN
408,Charlotte Russe,Flats,0.928571,0.714286,NaN
410,Charlotte Russe,Pumps,1.000000,0.833333,0.583333
411,Charlotte Russe,Sandals,0.866667,0.800000,0.733333
437,Christian Louboutin,Pumps,1.518868,2.122642,1.235849

In [141]:
retention_columns = [
    "condition_2_retention",
    "condition_3_retention",
    "condition_4_5_retention"
]

for column in retention_columns:
    usable_condition_analysis[f"{column}_percent"] = (
        usable_condition_analysis[column] * 100
    )

usable_condition_analysis[
    [
        "brand_name",
        "shoe_type",
        "condition_2_retention_percent",
        "condition_3_retention_percent",
        "condition_4_5_retention_percent"
    ]
].head(20)

condition_group,brand_name,shoe_type,condition_2_retention_percent,condition_3_retention_percent,condition_4_5_retention_percent
10,ALDO,Boots,67.391304,50.000000,NaN
14,ALDO,Pumps,64.516129,64.516129,NaN
18,ASICS,Athletic,64.583333,50.000000,33.333333
30,Adidas,Athletic,52.830189,31.132075,17.924528
32,Adidas,Fashion Sneakers,77.272727,62.121212,27.272727
35,Adidas,Sandals,75.000000,50.000000,NaN
82,American Eagle,Boots,95.454545,77.272727,NaN
84,American Eagle,Flats,100.000000,83.333333,NaN
87,American Eagle,Sandals,87.500000,75.000000,NaN
133,Ariat,Boots,83.098592,67.605634,43.661972
189,BCBGeneration,Pumps,63.636364,48.484848,NaN
266,Birkenstock,Sandals,78.205128,58.974359,33.333333
306,Brooks,Athletic,68.965517,44.827586,32.758621
386,Chaco,Sandals,92.561983,92.561983,50.413223
396,Chanel,Flats,46.109510,59.077810,NaN
406,Charlotte Russe,Boots,80.769231,65.384615,NaN
408,Charlotte Russe,Flats,92.857143,71.428571,NaN
410,Charlotte Russe,Pumps,100.000000,83.333333,58.333333
411,Charlotte Russe,Sandals,86.666667,80.000000,73.333333
437,Christian Louboutin,Pumps,151.886792,212.264151,123.584906

In [142]:
final_retention_table = usable_condition_analysis[
    [
        "brand_name",
        "shoe_type",
        "Condition 1_median_price",
        "Condition 2_median_price",
        "Condition 3_median_price",
        "Condition 4–5_median_price",
        "Condition 1_listing_count",
        "Condition 2_listing_count",
        "Condition 3_listing_count",
        "Condition 4–5_listing_count",
        "condition_2_retention_percent",
        "condition_3_retention_percent",
        "condition_4_5_retention_percent"
    ]
].copy()

final_retention_table.head(20)

condition_group,brand_name,shoe_type,Condition 1_median_price,Condition 2_median_price,Condition 3_median_price,Condition 4–5_median_price,Condition 1_listing_count,Condition 2_listing_count,Condition 3_listing_count,Condition 4–5_listing_count,condition_2_retention_percent,condition_3_retention_percent,condition_4_5_retention_percent
10,ALDO,Boots,46.0,31.0,23.0,12.0,13.0,31.0,52.0,9.0,67.391304,50.000000,NaN
14,ALDO,Pumps,31.0,20.0,20.0,14.0,11.0,41.0,78.0,9.0,64.516129,64.516129,NaN
18,ASICS,Athletic,48.0,31.0,24.0,16.0,42.0,83.0,184.0,20.0,64.583333,50.000000,33.333333
30,Adidas,Athletic,106.0,56.0,33.0,19.0,454.0,309.0,352.0,26.0,52.830189,31.132075,17.924528
32,Adidas,Fashion Sneakers,66.0,51.0,41.0,18.0,203.0,183.0,271.0,25.0,77.272727,62.121212,27.272727
35,Adidas,Sandals,28.0,21.0,14.0,15.0,25.0,23.0,41.0,3.0,75.000000,50.000000,NaN
82,American Eagle,Boots,22.0,21.0,17.0,15.0,17.0,32.0,50.0,5.0,95.454545,77.272727,NaN
84,American Eagle,Flats,12.0,12.0,10.0,13.0,15.0,21.0,51.0,2.0,100.000000,83.333333,NaN
87,American Eagle,Sandals,16.0,14.0,12.0,9.5,46.0,91.0,113.0,8.0,87.500000,75.000000,NaN
133,Ariat,Boots,71.0,59.0,48.0,31.0,25.0,53.0,112.0,12.0,83.098592,67.605634,43.661972
189,BCBGeneration,Pumps,33.0,21.0,16.0,13.0,13.0,25.0,40.0,4.0,63.636364,48.484848,NaN
266,Birkenstock,Sandals,78.0,61.0,46.0,26.0,129.0,166.0,471.0,82.0,78.205128,58.974359,33.333333
306,Brooks,Athletic,58.0,40.0,26.0,19.0,10.0,34.0,67.0,12.0,68.965517,44.827586,32.758621
386,Chaco,Sandals,60.5,56.0,56.0,30.5,16.0,59.0,193.0,12.0,92.561983,92.561983,50.413223
396,Chanel,Flats,173.5,80.0,102.5,64.5,12.0,11.0,12.0,8.0,46.109510,59.077810,NaN
406,Charlotte Russe,Boots,26.0,21.0,17.0,14.0,93.0,131.0,142.0,7.0,80.769231,65.384615,NaN
408,Charlotte Russe,Flats,14.0,13.0,10.0,8.0,20.0,23.0,22.0,3.0,92.857143,71.428571,NaN
410,Charlotte Russe,Pumps,18.0,18.0,15.0,10.5,79.0,174.0,163.0,16.0,100.000000,83.333333,58.333333
411,Charlotte Russe,Sandals,15.0,13.0,12.0,11.0,68.0,57.0,59.0,10.0,86.666667,80.000000,73.333333
437,Christian Louboutin,Pumps,106.0,161.0,225.0,131.0,47.0,61.0,131.0,17.0,151.886792,212.264151,123.584906

In [143]:
def classify_condition_pattern(row):
    retention_values = [
        row["condition_2_retention_percent"],
        row["condition_3_retention_percent"],
        row["condition_4_5_retention_percent"]
    ]

    valid_values = [
        value for value in retention_values
        if pd.notna(value)
    ]

    if any(value > 100 for value in valid_values):
        return "Non-monotonic price pattern"

    return "Expected decline pattern"


final_retention_table["condition_pattern"] = (
    final_retention_table.apply(
        classify_condition_pattern,
        axis=1
    )
)

In [145]:
print(final_retention_table.columns.tolist())

['brand_name', 'shoe_type', 'Condition 1_median_price', 'Condition 2_median_price', 'Condition 3_median_price', 'Condition 4–5_median_price', 'Condition 1_listing_count', 'Condition 2_listing_count', 'Condition 3_listing_count', 'Condition 4–5_listing_count', 'condition_2_retention_percent', 'condition_3_retention_percent', 'condition_4_5_retention_percent', 'condition_pattern']

In [146]:
final_retention_table[
    final_retention_table["brand_name"] == "Christian Louboutin"
][
    [
        "brand_name",
        "shoe_type",
        "condition_2_retention_percent",
        "condition_3_retention_percent",
        "condition_4_5_retention_percent",
        "condition_pattern"
    ]
]

condition_group,brand_name,shoe_type,condition_2_retention_percent,condition_3_retention_percent,condition_4_5_retention_percent,condition_pattern
437,Christian Louboutin,Pumps,151.886792,212.264151,123.584906,Non-monotonic price pattern

In [147]:
pattern_counts = (
    final_retention_table["condition_pattern"]
    .value_counts()
)

pattern_counts

condition_pattern
Expected decline pattern       125
Non-monotonic price pattern     10
Name: count, dtype: int64

In [148]:
pattern_percentages = (
    final_retention_table["condition_pattern"]
    .value_counts(normalize=True)
    .mul(100)
    .round(1)
)

pattern_percentages

condition_pattern
Expected decline pattern       92.6
Non-monotonic price pattern     7.4
Name: proportion, dtype: float64

In [149]:
results_path = Path(
    "../data/processed/brand_shoe_condition_retention.parquet"
)

csv_path = Path(
    "../outputs/tables/brand_shoe_condition_retention.csv"
)

final_retention_table.to_parquet(
    results_path,
    index=False
)

final_retention_table.to_csv(
    csv_path,
    index=False
)

print("Saved Parquet file:", results_path)
print("Saved CSV file:", csv_path)
print("Saved rows:", len(final_retention_table))

Saved Parquet file: ../data/processed/brand_shoe_condition_retention.parquet
Saved CSV file: ../outputs/tables/brand_shoe_condition_retention.csv
Saved rows: 135